// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5710494775882389493),
      name: 'Todo',
      lastPropertyId: const obx_int.IdUid(7, 8774199988964070051),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7268811204747592716),
            name: 'taskId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7290261532239531428),
            name: 'taskName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7729619753453189484),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8503918457953303115),
            name: 'dueDateTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6022723604781390153),
            name: 'isCompleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6229482138131879517),
            name: 'reminder',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8774199988964070051),
            name: 'repeat',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup, required obx_int.ModelDefinition model}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5710494775882389493),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Todo: obx_int.EntityDefinition<Todo>(
        model: _entities[0],
        toOneRelations: (Todo object) => [],
        toManyRelations: (Todo object) => {},
        getId: (Todo object) => object.taskId,
        setId: (Todo object, int id) {
          object.taskId = id;
        },
        objectToFB: (Todo object, fb.Builder fbb) {
          final taskNameOffset = fbb.writeString(object.taskName);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(8);
          fbb.addInt64(0, object.taskId);
          fbb.addOffset(1, taskNameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.dueDateTime?.millisecondsSinceEpoch);
          fbb.addBool(4, object.isCompleted);
          fbb.addBool(5, object.reminder);
          fbb.addFloat64(6, object.repeat);
          fbb.finish(fbb.endTable());
          return object.taskId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dueDateTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final taskIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final taskNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final dueDateTimeParam = dueDateTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dueDateTimeValue);
          final isCompletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final reminderParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final repeatParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = Todo(
              taskId: taskIdParam,
              taskName: taskNameParam,
              description: descriptionParam,
              dueDateTime: dueDateTimeParam,
              isCompleted: isCompletedParam,
              reminder: reminderParam,
              repeat: repeatParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Todo] entity fields to define ObjectBox queries.
class Todo_ {
  /// see [Todo.taskId]
  static final taskId =
      obx.QueryIntegerProperty<Todo>(_entities[0].properties[0]);

  /// see [Todo.taskName]
  static final taskName =
      obx.QueryStringProperty<Todo>(_entities[0].properties[1]);

  /// see [Todo.description]
  static final description =
      obx.QueryStringProperty<Todo>(_entities[0].properties[2]);

  /// see [Todo.dueDateTime]
  static final dueDateTime =
      obx.QueryDateProperty<Todo>(_entities[0].properties[3]);

  /// see [Todo.isCompleted]
  static final isCompleted =
      obx.QueryBooleanProperty<Todo>(_entities[0].properties[4]);

  /// see [Todo.reminder]
  static final reminder =
      obx.QueryBooleanProperty<Todo>(_entities[0].properties[5]);

  /// see [Todo.repeat]
  static final repeat =
      obx.QueryDoubleProperty<Todo>(_entities[0].properties[6]);
}
